import Foundation

/// The bundled ingredient hierarchy. Kept as Swift source rather than a
/// resource so it is type-checked and needs no bundle lookup.
///
/// Conventions:
/// - Keys are canonical ingredient or category names, lowercase.
/// - Values are direct parents only; the taxonomy walks the rest.
/// - A leaf ingredient with no category still gets an entry (empty parents)
///   when it needs to *win* longest-match over a shorter dairy/meat/etc. term:
///   "cream of tartar" must not resolve to "cream".
/// - Composite foods list every allergen they carry: pesto → pine nut + parmesan.
enum TaxonomyData {
    static let parents: [String: [String]] = [
        // MARK: Categories
        "dairy": [],
        "cheese": ["dairy"],
        "hard cheese": ["cheese"],
        "soft cheese": ["cheese"],
        "egg": [],
        "gluten": [],
        "wheat": ["gluten"],
        "barley": ["gluten"],
        "rye": ["gluten"],
        "legume": [],
        "nut": [],
        "tree nut": ["nut"],
        "peanut": ["legume", "nut"],
        "soy": ["legume"],
        "seafood": [],
        "fish": ["seafood"],
        "shellfish": ["seafood"],
        "crustacean": ["shellfish"],
        "mollusc": ["shellfish"],
        "meat": [],
        "red meat": ["meat"],
        "poultry": ["meat"],
        "pork": ["meat"],
        "beef": ["red meat"],
        "lamb": ["red meat"],
        "chicken": ["poultry"],
        "turkey": ["poultry"],
        "duck": ["poultry"],
        "sesame": [],
        "mustard": [],
        "celery": [],
        "alcohol": [],
        "nightshade": [],
        "allium": [],
        "corn": [],
        "coconut": [],
        "oat": [],
        "plant-based": [],

        // MARK: Dairy
        "milk": ["dairy"],
        "whole milk": ["milk"],
        "skim milk": ["milk"],
        "cream": ["dairy"],
        "heavy cream": ["cream"],
        "light cream": ["cream"],
        "half-and-half": ["cream"],
        "butter": ["dairy"],
        "unsalted butter": ["butter"],
        "salted butter": ["butter"],
        "ghee": ["dairy"],
        "yogurt": ["dairy"],
        "greek yogurt": ["yogurt"],
        "sour cream": ["dairy"],
        "creme fraiche": ["dairy"],
        "buttermilk": ["dairy"],
        "condensed milk": ["dairy"],
        "evaporated milk": ["dairy"],
        "whey": ["dairy"],
        "whey protein": ["whey"],
        "casein": ["dairy"],
        "ice cream": ["dairy"],
        "custard": ["dairy", "egg"],
        "parmesan": ["hard cheese"],
        "pecorino": ["hard cheese"],
        "gruyere": ["hard cheese"],
        "cheddar": ["cheese"],
        "mozzarella": ["cheese"],
        "feta": ["cheese"],
        "ricotta": ["soft cheese"],
        "brie": ["soft cheese"],
        "camembert": ["soft cheese"],
        "gouda": ["cheese"],
        "goat cheese": ["soft cheese"],
        "blue cheese": ["cheese"],
        "swiss cheese": ["cheese"],
        "mascarpone": ["soft cheese"],
        "cream cheese": ["soft cheese"],
        "cottage cheese": ["soft cheese"],
        "halloumi": ["cheese"],
        "paneer": ["cheese"],
        "monterey jack": ["cheese"],
        "provolone": ["cheese"],
        "burrata": ["soft cheese"],
        "queso fresco": ["cheese"],
        "vegan cheese": ["plant-based"],
        "vegan butter": ["plant-based"],
        "cream of tartar": [],
        "cocoa butter": [],
        "apple butter": [],
        "coconut milk": ["coconut"],
        "coconut cream": ["coconut"],
        "coconut oil": ["coconut"],
        "almond milk": ["almond"],
        "oat milk": ["oat"],
        "soy milk": ["soy"],
        "rice milk": [],
        "cashew cream": ["cashew"],

        // MARK: Egg
        "egg white": ["egg"],
        "egg yolk": ["egg"],
        "mayonnaise": ["egg"],
        "aioli": ["egg"],
        "meringue": ["egg"],
        "hollandaise": ["egg", "butter"],
        "caesar dressing": ["egg", "anchovy", "parmesan"],

        // MARK: Gluten grains
        "all-purpose flour": ["wheat"],
        "bread flour": ["wheat"],
        "cake flour": ["wheat"],
        "pastry flour": ["wheat"],
        "whole wheat flour": ["wheat"],
        "self-rising flour": ["wheat"],
        "flour": ["wheat"],
        "semolina": ["wheat"],
        "durum": ["wheat"],
        "spelt": ["wheat"],
        "farro": ["wheat"],
        "couscous": ["wheat"],
        "bulgur": ["wheat"],
        "seitan": ["wheat"],
        "pasta": ["wheat"],
        "spaghetti": ["pasta"],
        "penne": ["pasta"],
        "fettuccine": ["pasta"],
        "lasagna noodles": ["pasta"],
        "orzo": ["pasta"],
        "egg noodles": ["pasta", "egg"],
        "udon": ["wheat"],
        "ramen noodles": ["wheat"],
        "bread": ["wheat"],
        "breadcrumbs": ["wheat"],
        "panko": ["wheat"],
        "croutons": ["wheat"],
        "flour tortilla": ["wheat"],
        "pita": ["wheat"],
        "naan": ["wheat"],
        "graham cracker": ["wheat"],
        "puff pastry": ["wheat", "butter"],
        "phyllo": ["wheat"],
        "wheat berries": ["wheat"],
        "beer": ["barley", "alcohol"],
        "malt": ["barley"],
        "malt vinegar": ["barley"],
        "rye flour": ["rye"],
        "rye bread": ["rye"],
        "almond flour": ["almond"],
        "rice flour": [],
        "chickpea flour": ["chickpea"],
        "coconut flour": ["coconut"],
        "rolled oats": ["oat"],

        // MARK: Legumes, soy, peanut
        "lentil": ["legume"],
        "chickpea": ["legume"],
        "hummus": ["chickpea", "sesame"],
        "black bean": ["legume"],
        "kidney bean": ["legume"],
        "pinto bean": ["legume"],
        "cannellini bean": ["legume"],
        "white bean": ["legume"],
        "navy bean": ["legume"],
        "bean": ["legume"],
        "green bean": [],
        "pea": ["legume"],
        "green pea": ["pea"],
        "split pea": ["pea"],
        "snap pea": ["pea"],
        "peanut butter": ["peanut"],
        "peanut oil": ["peanut"],
        "satay sauce": ["peanut"],
        "soybean": ["soy"],
        "tofu": ["soy"],
        "tempeh": ["soy"],
        "edamame": ["soy"],
        "soy sauce": ["soy", "wheat"],
        "tamari": ["soy"],
        "miso": ["soy"],
        "natto": ["soy"],
        "hoisin sauce": ["soy", "wheat"],
        "teriyaki sauce": ["soy", "wheat"],

        // MARK: Tree nuts
        "almond": ["tree nut"],
        "walnut": ["tree nut"],
        "cashew": ["tree nut"],
        "pecan": ["tree nut"],
        "pistachio": ["tree nut"],
        "hazelnut": ["tree nut"],
        "macadamia": ["tree nut"],
        "brazil nut": ["tree nut"],
        "pine nut": ["tree nut"],
        "chestnut": ["tree nut"],
        "almond butter": ["almond"],
        "marzipan": ["almond"],
        "nutella": ["hazelnut", "dairy"],
        "pesto": ["pine nut", "parmesan"],
        "praline": ["pecan"],
        "nutmeg": [],
        "water chestnut": [],
        "butternut squash": [],

        // MARK: Seafood
        "shrimp": ["crustacean"],
        "prawn": ["crustacean"],
        "crab": ["crustacean"],
        "lobster": ["crustacean"],
        "crayfish": ["crustacean"],
        "langoustine": ["crustacean"],
        "shrimp paste": ["shrimp"],
        "clam": ["mollusc"],
        "mussel": ["mollusc"],
        "oyster": ["mollusc"],
        "scallop": ["mollusc"],
        "squid": ["mollusc"],
        "octopus": ["mollusc"],
        "escargot": ["mollusc"],
        "oyster sauce": ["oyster"],
        "salmon": ["fish"],
        "tuna": ["fish"],
        "cod": ["fish"],
        "haddock": ["fish"],
        "tilapia": ["fish"],
        "anchovy": ["fish"],
        "sardine": ["fish"],
        "mackerel": ["fish"],
        "trout": ["fish"],
        "halibut": ["fish"],
        "sea bass": ["fish"],
        "snapper": ["fish"],
        "swordfish": ["fish"],
        "herring": ["fish"],
        "fish sauce": ["fish"],
        "worcestershire sauce": ["anchovy"],
        "surimi": ["fish"],

        // MARK: Meat
        "ground beef": ["beef"],
        "steak": ["beef"],
        "brisket": ["beef"],
        "beef broth": ["beef"],
        "beef stock": ["beef"],
        "veal": ["red meat"],
        "venison": ["red meat"],
        "goat": ["red meat"],
        "bacon": ["pork"],
        "ham": ["pork"],
        "prosciutto": ["pork"],
        "pancetta": ["pork"],
        "sausage": ["pork"],
        "pork belly": ["pork"],
        "pork chop": ["pork"],
        "pork shoulder": ["pork"],
        "chorizo": ["pork"],
        "salami": ["pork"],
        "pepperoni": ["pork"],
        "lard": ["pork"],
        "gelatin": ["meat"],
        "chicken breast": ["chicken"],
        "chicken thigh": ["chicken"],
        "chicken wing": ["chicken"],
        "ground chicken": ["chicken"],
        "chicken stock": ["chicken"],
        "chicken broth": ["chicken"],
        "ground turkey": ["turkey"],
        "goose": ["poultry"],
        "quail": ["poultry"],

        // MARK: Sesame, mustard, celery
        "tahini": ["sesame"],
        "sesame oil": ["sesame"],
        "sesame seed": ["sesame"],
        "dijon mustard": ["mustard"],
        "mustard seed": ["mustard"],
        "whole grain mustard": ["mustard"],
        "celery seed": ["celery"],
        "celery salt": ["celery"],
        "celeriac": ["celery"],

        // MARK: Alcohol
        "wine": ["alcohol"],
        "red wine": ["wine"],
        "white wine": ["wine"],
        "cooking wine": ["wine"],
        "vodka": ["alcohol"],
        "rum": ["alcohol"],
        "whiskey": ["alcohol"],
        "bourbon": ["alcohol"],
        "brandy": ["alcohol"],
        "sake": ["alcohol"],
        "mirin": ["alcohol"],
        "vermouth": ["alcohol"],
        "tequila": ["alcohol"],
        "gin": ["alcohol"],
        "liqueur": ["alcohol"],
        "red wine vinegar": [],
        "white wine vinegar": [],
        "rice wine vinegar": [],

        // MARK: Nightshades and alliums
        "tomato": ["nightshade"],
        "tomato paste": ["tomato"],
        "tomato sauce": ["tomato"],
        "sun-dried tomato": ["tomato"],
        "ketchup": ["tomato"],
        "potato": ["nightshade"],
        "sweet potato": [],
        "eggplant": ["nightshade"],
        "bell pepper": ["nightshade"],
        "chili pepper": ["nightshade"],
        "jalapeno": ["nightshade"],
        "paprika": ["nightshade"],
        "cayenne": ["nightshade"],
        "chili powder": ["nightshade"],
        "chili flakes": ["nightshade"],
        "black pepper": [],
        "white pepper": [],
        "onion": ["allium"],
        "red onion": ["onion"],
        "yellow onion": ["onion"],
        "garlic": ["allium"],
        "garlic powder": ["garlic"],
        "shallot": ["allium"],
        "leek": ["allium"],
        "spring onion": ["allium"],
        "chive": ["allium"],
        "onion powder": ["onion"],

        // MARK: Corn
        "cornstarch": ["corn"],
        "cornmeal": ["corn"],
        "polenta": ["corn"],
        "corn syrup": ["corn"],
        "corn tortilla": ["corn"],
        "popcorn": ["corn"],

        // MARK: Staples with no allergen category
        // Listed so they are recognised terms: "with chicken and rice" needs
        // "rice" to resolve, and nutrition lookup wants a canonical name.
        "rice": [], "brown rice": ["rice"], "white rice": ["rice"], "basmati rice": ["rice"],
        "jasmine rice": ["rice"], "quinoa": [], "sugar": [], "brown sugar": ["sugar"],
        "powdered sugar": ["sugar"], "superfine sugar": ["sugar"], "honey": [], "maple syrup": [],
        "olive oil": [], "vegetable oil": [], "canola oil": [], "avocado oil": [],
        "broccoli": [], "spinach": [], "kale": [], "carrot": [], "zucchini": [], "mushroom": [],
        "avocado": [], "banana": [], "apple": [], "lemon": [], "lime": [], "orange": [],
        "blueberry": [], "strawberry": [], "raspberry": [], "cucumber": [], "lettuce": [],
        "cabbage": [], "cauliflower": [], "asparagus": [], "beet": [], "pumpkin": [],
        "squash": [], "ginger": [], "coriander": [], "parsley": [], "basil": [], "mint": [],
        "dill": [], "cinnamon": [], "cumin": [], "turmeric": [], "vanilla extract": [],
        "baking soda": [], "baking powder": [], "yeast": [], "salt": [], "water": [],
        "stock": [], "vegetable stock": ["stock"], "vegetable broth": ["stock"],
        "arugula": [], "zucchini noodles": ["zucchini"], "dark chocolate": [],
        "milk chocolate": ["dairy"], "white chocolate": ["dairy"], "chocolate chips": [],
        "cocoa powder": [], "coffee": [],
    ]

    static let aliases: [String: String] = [
        "parmigiano reggiano": "parmesan",
        "parmigiano": "parmesan",
        "parmesan cheese": "parmesan",
        "pecorino romano": "pecorino",
        "groundnut": "peanut",
        "groundnut oil": "peanut oil",
        "monkey nut": "peanut",
        "scallion": "spring onion",
        "green onion": "spring onion",
        "ap flour": "all-purpose flour",
        "plain flour": "all-purpose flour",
        "strong flour": "bread flour",
        "strong white flour": "bread flour",
        "wholemeal flour": "whole wheat flour",
        "aubergine": "eggplant",
        "calamari": "squid",
        "double cream": "heavy cream",
        "whipping cream": "heavy cream",
        "single cream": "light cream",
        "half and half": "half-and-half",
        "bicarbonate of soda": "baking soda",
        "bicarb": "baking soda",
        "caster sugar": "superfine sugar",
        "icing sugar": "powdered sugar",
        "confectioners sugar": "powdered sugar",
        "cilantro": "coriander",
        "coriander leaves": "coriander",
        "courgette": "zucchini",
        "capsicum": "bell pepper",
        "rocket": "arugula",
        "prawns": "prawn",
        "shrimps": "shrimp",
        "mince": "ground beef",
        "minced beef": "ground beef",
        "beef mince": "ground beef",
        "streaky bacon": "bacon",
        "rashers": "bacon",
        "garbanzo bean": "chickpea",
        "garbanzo": "chickpea",
        "filbert": "hazelnut",
        "pignoli": "pine nut",
        "cornflour": "cornstarch",
        "maize": "corn",
        "sweetcorn": "corn",
        "soya": "soy",
        "soya sauce": "soy sauce",
        "shoyu": "soy sauce",
        "bean curd": "tofu",
        "nam pla": "fish sauce",
        "worcester sauce": "worcestershire sauce",
        "rapeseed oil": "canola oil",
        "gelatine": "gelatin",
        "yoghurt": "yogurt",
        "greek yoghurt": "greek yogurt",
        "mozzarella cheese": "mozzarella",
        "cheddar cheese": "cheddar",
        "feta cheese": "feta",
        "goats cheese": "goat cheese",
        "goat's cheese": "goat cheese",
        "swiss": "swiss cheese",
        "chilli": "chili pepper",
        "chilli powder": "chili powder",
        "chilli flakes": "chili flakes",
        "red pepper flakes": "chili flakes",
        "spring onions": "spring onion",
        "eggs": "egg",
        "egg whites": "egg white",
        "egg yolks": "egg yolk",
    ]
}
